// from mcqueenorama at gmail dot com; see also
// http://groups-beta.google.com/group/Google-Maps-API/browse_thread/thread/fdb49a801fd6bf7d/afafb60f21f3d556

var g_map;

function zoomIncrement(boundsSize, dataSize, exp) {
    var new_exp;
    if ((dataSize.width > boundsSize.width * Math.pow(2, exp)) || (dataSize.height > boundsSize.height * Math.pow(2, exp))) {
        if (exp < 0)
            return exp + 1;
        new_exp = exp + 1;
    } else {
        if (exp > 0)
            return exp;
        new_exp = exp - 1;
    }

    return zoomIncrement(boundsSize, dataSize, new_exp);
} 

function _makeMarker(map, x) {
    // location
    var point = new GLatLng(x.getElementsByTagName("point")[0].getAttribute("lat"), x.getElementsByTagName("point")[0].getAttribute("lng"));
    // icon
    var icon = new GIcon();
    var imageurl = x.getElementsByTagName("icon")[0].getAttribute("image");
    // for safari, where & => &#38; and .replace doesn't seem to work
    while (imageurl.indexOf('&#38;') != -1) {
        var pos = imageurl.indexOf('&#38;');
        imageurl = imageurl.substring(0, pos) + "&" + imageurl.substring(pos + "&#38;".length);
    }
    icon.image = imageurl;
    icon.shadow = "http://www.google.com/mapfiles/shadow50.png";
    icon.iconSize = new GSize(40, 34);
    icon.shadowSize = new GSize(67, 34);
    icon.iconAnchor = new GPoint(19, 34);
    icon.infoWindowAnchor = new GPoint(19, 0);
    icon.infoShadowAnchor = new GPoint(38, 25);

    // marker
    var marker = new GMarker(point, icon);
    var info = x.getElementsByTagName("div")[0];

    GEvent.addListener(marker, "click", function() {
        marker.openInfoWindow(info);
        map.panTo(point);
    });

    return marker;
}

// displays xml generated by longwell
function _Gdisplay(x) {
    document.getElementById('loading').style.display='none';
    if (GBrowserIsCompatible()) {
	// new map
        var map = new GMap2(document.getElementById("map"));
	g_map = map;

	// center
        var mapinfo = x.documentElement.getElementsByTagName("center");
	var center = new GLatLng(mapinfo[0].getAttribute("lat"), mapinfo[0].getAttribute("lng"));
	map.setCenter(center);

	// zoom
        map.setZoom(8);
        var originalBounds = map.getBounds().toSpan();
        var originalZoomLevel = map.getZoom();

        var originalLatSpan = Math.abs(originalBounds.lat());
        var originalLongSpan = Math.abs(originalBounds.lng());
        var originalBounds = new GSize(originalLongSpan, originalLatSpan);
        var dataBounds = new GSize(x.documentElement.getElementsByTagName("span")[0].getAttribute("lng"), x.documentElement.getElementsByTagName("span")[0].getAttribute("lat"));

        map.setZoom(originalZoomLevel - zoomIncrement(originalBounds, dataBounds, 0));

	// add controls
        map.addControl(new GLargeMapControl());
        map.addControl(new GMapTypeControl());

	// go through XML for each location
        var markers = x.documentElement.getElementsByTagName("location");
        for (var i = 0; i < markers.length; i++) {
            var marker = _makeMarker(map, markers[i]);
            map.addOverlay(marker);
        }

        // legend - if it doesn't work, don't worry, just assume it isn't there
        try {
            var legend = x.documentElement.getElementsByTagName("legend")[0];
            window.parent.Map_setLegend(legend);
        } catch (e) { }
    }
}

// run after page is loaded
function _initGMap() {
    var urlOffset = document.location.search.indexOf("url=") + "url=".length;
    var url = document.location.search.substring(urlOffset);
    url = unescape(url);
    try {
        var xmlhttp = GXmlHttp.create();
        xmlhttp.open("GET", url, true);
        xmlhttp.onreadystatechange=function() {
            if (xmlhttp.readyState==4) {
                _Gdisplay(xmlhttp.responseXML);
            }
        }
        xmlhttp.send(null); // Whoops, IE *needs* this to be last, Moz is lenient.
    } catch (e) {
        // um...this try/catch seems to enable Safari functionality...
    }
}

function GMapToFacetRestriction() {
    var bounds = g_map.getBounds();
    var sw = bounds.getSouthWest();
    var ne = bounds.getNorthEast();
    // lng1,lat1,lng2,lat2
    var val = sw.x + "~" + sw.y + "|" + ne.x + "~" + ne.y;
    val = val.replace(/ /g,"");
    var mapFacetURL = parent.document.getElementById("restrictor").getAttribute("mapRestrictorURL") + escape(val) + "&";

    parent.window.location = mapFacetURL;
}
